#!/bin/bash
#---------------------------------------------------------------------------
# @(#)$Id$
#title          :ngo_fw.sh
#description    :Uses iptables and ipset to block ip's in known blacklist.
#options        :ngo_fw.sh whitelist | loadatboot | install | installpsad
#
# Some hosting services such as RamNode will ban you for using > 90% of the cpu!!!
# So we recommend installing cpulimit and limiting to 20% of cpu usage when 
# calling this script.
#
# cpulimit -z -l 20 /usr/local/bin/ngo_fw.sh
# cpulimit dosn't like scripts writing to stdout/stderr so them redirect to 
# an output file.
#
#---------------------------------------------------------------------------
SCRIPT_NAME=`basename ${BASH_SOURCE[0]}` #Script File Name
HOST_NAME=`uname -n` #hostname
BL_DIR="/var/lib/ngo_fw" # Where we keep some files.
# Default syslog messages priority and tag.
LOG_PRI="local0.notice"
LOG_TAG="[$SCRIPT_NAME]"
# Your ip if you are connected by ssh
WL_IP=`who | grep pts | awk '{print $5}' | cut -f2 -d"(" | cut -f1 -d")" | uniq`
# Your internal net
HOME_NET4=`ip addr show | grep inet | awk '{print $2}' | cut -f2 -d: | grep -v 127 | sed '/^$/d' | cut -f1 -d/`
MASK4=/`ip addr show | grep inet | awk '{print $2}' | cut -f2 -d: | grep -v 127 | sed '/^$/d' | cut -f2 -d/`
HOME_NET6=`ip addr show | grep inet6 | awk '{print $2}' | grep -v ::1 | cut -f1 -d/`
MASK6=/`ip addr show | grep inet6 | awk '{print $2}' | grep -v ::1 | cut -f2 -d/`
PSAD_AUTODL=`ip addr show | grep inet | awk '{print $2}' | sed 's/$/ 0;/'`
# Set to empty string if you don't want error emails. Otherwise, set to an admin email.
MAIL_ADMIN="root@localhost"
# Logging is enabled for the following ports this is so we can do later audit checks
# in case we are droping legitimate traffic.
TCP_PORTS="22,80,443,2222"
UDP_PORTS="53"
# If PSAD is installed then block Danger Level = $DL and above attackers
# each time the blacklist are reloaded.
DL=3
# Retrieve new blacklist only when they are older then BL_AGE
BL_AGE="23 hours ago"

if [[ $1 != "" ]]; then OPTS=$1; else OPTS="null"; fi

if [ -d "$BL_DIR" ]; then
  exec > $BL_DIR/ngo_fw.out 2>&1
else
  mkdir -p $BL_DIR
  exec > $BL_DIR/ngo_fw.out 2>&1
fi

if [ $OPTS = "installpsad" ]; then
  clear
    echo "Installing PSAD"
    echo -e "apt install -y psad\n"
    debconf-set-selections <<< "postfix postfix/main_mailer_type select No configuration"
    apt install -y psad
    update-rc.d psad enable
    cat <(crontab -l) <(echo "@daily  root  psad --sig-update && psad -H > $BL_DIR/psad_cron_update.log" ) | crontab -
    cp /etc/psad/psad.conf /etc/psad/psad.conf.ori
    sed -i "s/EMAIL_ADDRESSES             root@localhost;/EMAIL_ADDRESSES             $MAIL_ADMIN;/" /etc/psad/psad.conf
    sed -i "s/_CHANGEME_/$HOST_NAME/g" /etc/psad/psad.conf
    #sed -i "s/HOME_NET                    any;/HOME_NET                    $HOME_NET4\\$MASK4;/" /etc/psad/psad.conf
    sed -i "s/HOME_NET                    any;/HOME_NET                    NOT_USED;/" /etc/psad/psad.conf
    sed -i '/ENABLE_AUTO_IDS             N;/ c\ENABLE_AUTO_IDS             Y;' /etc/psad/psad.conf
    sed -i '/AUTO_IDS_DANGER_LEVEL/ c\AUTO_IDS_DANGER_LEVEL 4;' /etc/psad/psad.conf
    sed -i "s/IPT_SYSLOG_FILE             \/var\/log\/messages;/IPT_SYSLOG_FILE             \/var\/log\/ngo_fw_logs;/" /etc/psad/psad.conf
    echo -e "\n$PSAD_AUTODL" >> /etc/psad/auto_dl
    psad --sig-update
    psad -H

    if [ -f /etc/init.d/rsyslog ]; then
      if [ -f /etc/rsyslog.d/30-ngo_fw.conf ]; then
        sed -i "\$a # Log kernel messages generated by iptables to file \n:msg, contains, \"[NGO_FW LOG]\" -/var/log/ngo_fw_logs \n& stop" /etc/rsyslog.d/30-ngo_fw.conf
      else
      echo '# Log kernel messages generated by iptables to file
:msg, contains, "[NGO_FW LOG]" -/var/log/ngo_fw_logs
& stop' > /etc/rsyslog.d/30-ngo_fw.conf
      fi
      service rsyslog restart
    fi
    echo '/var/log/ngo_fw_logs
          {
              rotate 4
              weekly
              missingok
              notifempty
              compress
              delaycompress
              sharedscripts
              postrotate
                  invoke-rc.d rsyslog reload >/dev/null 2>&1 || true
              endscript
          }' >> /etc/logrotate.d/ngo_fw


    echo "PSAD installed successfully"
    exit 0
fi
#
if [ $OPTS = "install" ]; then
  clear
  if [ -f "/usr/local/bin/$SCRIPT_NAME" ]; then
    echo -e "\nScript file exist on: /usr/local/bin/$SCRIPT_NAME"
    exit 0
  else
    echo -e "apt install -y cpulimit ipset iptables-persistent\n"
    debconf-set-selections <<< "iptables-persistent iptables-persistent/autosave_v4 boolean true" 
    debconf-set-selections <<< "iptables-persistent iptables-persistent/autosave_v6 boolean true" 
    apt install -y cpulimit ipset iptables-persistent
    echo "update-rc.d iptables-persistent enable"
    update-rc.d iptables-persistent enable
    cp -v iptables4 /etc/iptables/rules.v4
    p -v iptables6 /etc/iptables/rules.v6
    echo "cp -fv $SCRIPT_NAME /usr/local/bin/"
    cp -fv $SCRIPT_NAME /usr/local/bin/
    echo "chown root:root /usr/local/bin/ngo_fw.sh"
    chown root:root /usr/local/bin/$SCRIPT_NAME
    echo "chmod +x /usr/local/bin/$SCRIPT_NAME"
    chmod +x /usr/local/bin/$SCRIPT_NAME
    echo "mkdir -pv $BL_DIR/"
    mkdir -pv $BL_DIR/
    echo -e "touch $BL_DIR/{whitelist.txt,blacklist.txt}\n"
    touch $BL_DIR/{whitelist.txt,blacklist.txt}
      if [[ $WL_IP != "" ]]; then
        echo "$WL_IP" > $BL_DIR/whitelist.txt
      else
        echo "Nothing to do on whitelist.txt"
      fi
    echo 'cat <(crontab -l) <(echo "@daily          root    cpulimit -z -l 20 /usr/local/bin/ngo_fw.sh") | crontab -'
    cat <(crontab -l) <(echo "# SECURITY NGO_FW SCRIPT") | crontab -
    #cat <(crontab -l) <(echo "@reboot root  sleep 60 && cpulimit -z -l 20 /usr/local/bin/$SCRIPT_NAME &") | crontab -
    
    if [ -f "/etc/rc.local" ]; then
      sed -i "\$i /bin/bash /usr/local/bin/ngo_fw.sh loadatboot\n" /etc/rc.local
    else
      systemctl enable rc-local
      touch /etc/rc.local && chmod +x /etc/rc.local
      echo '#!/bin/bash' > /etc/rc.local
      echo -e "\nexit" >> /etc/rc.local
      sed -i "\$i /bin/bash /usr/local/bin/ngo_fw.sh loadatboot\n" /etc/rc.local
    exit
   fi
    cat <(crontab -l) <(echo "@daily  root  cpulimit -z -l 20 /usr/local/bin/$SCRIPT_NAME &") | crontab -

    if [ -f /etc/init.d/rsyslog ]; then
      if [ -f /etc/rsyslog.d/30-ngo_fw.conf ]; then
        sed -i "\$a # Log kernel messages generated by iptables to file \n:msg, contains, \"[NGO_FW BLACKLIST DROP]\" -/var/log/ngo_fw_bl_drops\n & stop" /etc/rsyslog.d/30-ngo_fw.conf
      else
      echo '# Log kernel messages generated by iptables to file
:msg, contains, "[NGO_FW BLACKLIST DROP]" -/var/log/ngo_fw_bl_drops
& stop' > /etc/rsyslog.d/30-ngo_fw.conf
      fi
      service rsyslog restart
    fi
    echo '/var/log/ngo_fw_bl_drops
          {
              rotate 4
              weekly
              missingok
              notifempty
              compress
              delaycompress
              sharedscripts
              postrotate
                  invoke-rc.d rsyslog reload >/dev/null 2>&1 || true
              endscript

          }' >> /etc/logrotate.d/ngo_fw
  fi
  echo -e "\nPre-req is installed!"
  exit 0
fi
#---------------------------------------------------------------------------
# FUNCTIONS
#---------------------------------------------------------------------------

# logmessage <msg_text>
logmessage () {
  MSG="$1"
  logger -s -p $LOG_PRI -t $LOG_TAG "$MSG"
}

# <ips> goodinbadnets
# - returns whitelist <ips> that that are in blacklist.
goodinbadnets () {
  myips=""
  for good in `ipset list whitelist_ips | egrep -E "^[1-9]"`
  do
   myip=`ipset test blacklist_nets_n $good 2>&1 | grep "is in" | awk '{print $1}'`
   if [ -n "$myip" ];then
     myips="$myips $myip"
   fi
  done
  echo $myips
}

# blacklistit <ip/cdr> <listname>
#  - blacklist the given <ip/cdr> to blacklist_nets_n or blacklist_ips_n
#  - also checks if the <ip/cdr> blacklist one of your whitelisted ips, and 
#  if so it will remove it from the blacklist and warn you.
blacklistit () {
 IP=$1
 LISTNAME=$2
 if echo "$IP" | egrep -q "\/[0-9]+"; then
   ipset add blacklist_nets_n $IP -exist
   badip=`goodinbadnets`
   if [ -n "$badip" ]; then
     error_msg="ERROR Your whitelist IP $badip has been blacklisted in $LISTNAME"
     logmessage "$error_msg"
     ERROR_MSGS="$ERROR_MSGS\n$error_msg"
     ipset del blacklist_nets_n $IP
   fi
        
 else
   if ipset test whitelist_ips $IP 2> /dev/null; then
     error_msg="ERROR Your whitelist IP $IP has been blacklisted in $LISTNAME"
     logmessage "$error_msg"
     ERROR_MSGS="$ERROR_MSGS\n$error_msg"
   else 
     ipset add blacklist_ips_n $IP -exist
   fi
 fi
}

# loadblacklist <name> <url>
# - loads standard form blacklist from <url> website, labels cache files with <name>
loadblacklist () {
  BL_NAME=$1
  BL_URL=$2
  BL_FILE="$BL_DIR/$BL_NAME.txt"

  if [ ! -f "$BL_FILE" ] || [ $(date +%s -r "$BL_FILE") -lt $(date +%s --date="$BL_AGE") ]; then
    echo "-- getting fresh $BL_NAME from $BL_URL"
    wget -q -t 2 --output-document=$BL_FILE $BL_URL --no-check-certificate
  fi

  if [ -f "$BL_FILE" ]; then
    echo "-- loading $BL_NAME from $BL_FILE"
    # strip comments - mac address and ipv6 not supported yet so strip :
    grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(/[0-9]+)?' $BL_FILE > ${BL_FILE}.filtered
    echo "-- loading $BL_NAME - `wc -l ${BL_FILE}.filtered` entries"
    
    for ip in `cat ${BL_FILE}.filtered`; do
      blacklistit $ip $BL_NAME
    done
  fi
}

# load your good ip's
loadcustomwhitelist () {
# load fresh white list each time as the list should be small.
ipset flush whitelist_ips_n
WL_CUSTOM="$BL_DIR/whitelist.txt"
count=0
if [ -f "$WL_CUSTOM" ]; then
  for ip in `grep -Ev "^#|^ *$" $WL_CUSTOM | sed -e "s/#.*$//" -e "s/[^.0-9\/]//g"`; do
     ipset add whitelist_ips_n $ip -exist
     count=$((count+1))
  done
fi
echo "-- loaded `ipset list whitelist_ips_n | egrep "^[1-9]"  | wc -l` entries from whitelist "
echo "-- loaded $count entries from $WL_CUSTOM"
}

loadcustomblacklist() {
# load your personal custom blacklist.
BL_CUSTOM="$BL_DIR/blacklist.txt"
count=0
if [ -f "$BL_CUSTOM" ]; then
  for ip in `grep -Ev "^#|^ *$" $BL_CUSTOM | sed -e "s/#.*$//" -e "s/[^.0-9\/]//g"`; do
    blacklistit $ip $BLACKLIST
    count=$((count+1))
  done
fi
echo "-- loaded `ipset list blacklist_ips_n | egrep "^[1-9]"  | wc -l` entries from blacklist "
echo "-- loaded $count entries from $BL_CUSTOM"
}

loadcustomiptables () {
#
# Setup our firewall ip chains 
#
if ! iptables -L blacklist -n > /dev/null 2>&1; then

  echo "-- creating blacklist iptables rules for first time"
  iptables -N blacklist

  # insert the smaller set first.
  iptables -I INPUT  \
       -m set --match-set blacklist_ips src -j blacklist

  iptables -I OUTPUT  \
       -m set --match-set blacklist_ips dst -j blacklist

  iptables -I INPUT \
       -m set --match-set blacklist_nets src -j blacklist

  iptables -I OUTPUT \
       -m set --match-set blacklist_nets dst -j blacklist

  iptables -I INPUT 15 \
        -m set --match-set whitelist_ips src -p tcp -m tcp --dport 22 -j ACCEPT
  
#  iptables -I INPUT 17 \
#        -m set --match-set whitelist_ips src -p tcp -m tcp --dport 2222 -j ACCEPT

  # keep a record of our business traffic ports.
  # so we can check if we blocked legitimate traffic if need be.
  # DNS and http/https are most typical legit ports
  iptables -A blacklist -p tcp -m multiport --dports $TCP_PORTS \
         -m limit --limit 5/min \
         -j LOG --log-prefix "[NGO_FW BLACKLIST DROP] "
  #  iptables -A blacklist -p udp -m multiport --dport $UDP_PORTS \
  #         -m limit --limit 5/min \
  #         -j LOG --log-prefix "[NGO_FW BLACKLIST DROP] "
  iptables -A blacklist -m state --state NEW -j DROP 
fi
}

# Only reload whitelist
if [ $OPTS = "whitelist" ]; then
  echo -e "\nWhitelist is reloading"
  if ! ipset list whitelist_ips > /dev/null 2>&1
  then
    echo "-- creating whitelist_ips ipset as does not exist."
    ipset create whitelist_ips hash:ip hashsize 4096 maxelem 262144
    if [ -f "$BL_DIR/whitelist_ips.sav" ]; then
      echo "-- importing from save file $BL_DIR/whitelist_ips.sav"
      grep -v "create" $BL_DIR/whitelist_ips.sav | ipset restore 
    fi
  fi
  ipset create whitelist_ips_n hash:ip hashsize 4096 maxelem 262144 2> /dev/null
  loadcustomwhitelist
  ipset swap whitelist_ips_n whitelist_ips
  ipset destroy whitelist_ips_n
  ipset save whitelist_ips  > $BL_DIR/whitelist_ips.sav
  echo -e "\nWhitelist is reloaded"
  exit 0
fi

# Only load custom iptables
if [ $OPTS = "loadatboot" ]; then
  echo -e "\nWhitelist is reloading"
  if ! ipset list whitelist_ips > /dev/null 2>&1
  then
    echo "-- creating whitelist_ips ipset as does not exist."
    ipset create whitelist_ips hash:ip hashsize 4096 maxelem 262144
    if [ -f "$BL_DIR/whitelist_ips.sav" ]; then
      echo "-- importing from save file $BL_DIR/whitelist_ips.sav"
      grep -v "create" $BL_DIR/whitelist_ips.sav | ipset restore 
    fi
  fi
  ipset create whitelist_ips_n hash:ip hashsize 4096 maxelem 262144 2> /dev/null
  loadcustomwhitelist
  ipset swap whitelist_ips_n whitelist_ips
  ipset destroy whitelist_ips_n
  ipset save whitelist_ips  > $BL_DIR/whitelist_ips.sav
  echo -e "\nWhitelist is reloaded"

  if ! ipset list blacklist_ips > /dev/null 2>&1
  then
    echo "-- creating blacklist_ips ipset as does not exist."
    ipset create blacklist_ips hash:ip hashsize 4096 maxelem 262144
    if [ -f "$BL_DIR/blacklist_ips.sav" ]; then
      echo "-- importing from save file $BL_DIR/blacklist_ips.sav"
      grep -v "create" $BL_DIR/blacklist_ips.sav | ipset restore 
    fi
  fi
  if ! ipset list blacklist_nets > /dev/null 2>&1
  then
    echo "-- creating blacklist_nets ipset as does not exist."
    ipset create blacklist_nets hash:net hashsize 4096 maxelem 262144
    if [ -f "$BL_DIR/blacklist_nets.sav" ]; then
      echo "-- importing from save file $BL_DIR/blacklist_nets.sav"
      grep -v "create" $BL_DIR/blacklist_nets.sav | ipset restore 
    fi
  fi

  touch /var/log/ngo_fw_logs && chown syslog:adm /var/log/ngo_fw_logs
  touch /var/log/ngo_fw_bl_drops && chown syslog:adm /var/log/ngo_fw_bl_drops

  echo -e "\nConfigure IPTABLES"
  loadcustomiptables

  if [ -f /etc/init.d/rsyslog ]; then
    service rsyslog restart
  fi

  echo -e "\nConfigure IPTABLES done"
  exit 0
fi
#---------------------------------------------------------------------------
# MAIN
#---------------------------------------------------------------------------

# concatenated list of all error message
ERROR_MSGS=""

if ! which ipset > /dev/null 2>&1;then
  echo "ERROR: You must install 'ipset'"
  exit 1
fi

logmessage "script started"

# Create temporary swap ipsets
ipset create blacklist_ips_n hash:ip hashsize 4096 maxelem 262144 2> /dev/null
ipset flush blacklist_ips_n

ipset create blacklist_nets_n hash:net hashsize 4096 maxelem 262144 2> /dev/null
ipset flush blacklist_nets_n

ipset create whitelist_ips_n hash:ip hashsize 4096 maxelem 262144 2> /dev/null
ipset flush whitelist_ips_n

#
# Setup the active ipsets if they don't yet exist.
# Load them from last save sets to speed up load times in cases of reboot
# and ensure protection faster.
#
if ! ipset list blacklist_ips > /dev/null 2>&1
then
  echo "-- creating blacklist_ips ipset as does not exist."
  ipset create blacklist_ips hash:ip hashsize 4096 maxelem 262144
  if [ -f "$BL_DIR/blacklist_ips.sav" ]; then
    echo "-- importing from save file $BL_DIR/blacklist_ips.sav"
    grep -v "create" $BL_DIR/blacklist_ips.sav | ipset restore 
  fi
fi
#
if ! ipset list blacklist_nets > /dev/null 2>&1
then
  echo "-- creating blacklist_nets ipset as does not exist."
  ipset create blacklist_nets hash:net hashsize 4096 maxelem 262144
  if [ -f "$BL_DIR/blacklist_nets.sav" ]; then
    echo "-- importing from save file $BL_DIR/blacklist_nets.sav"
    grep -v "create" $BL_DIR/blacklist_nets.sav | ipset restore 
  fi
fi
#
if ! ipset list whitelist_ips > /dev/null 2>&1
then
  echo "-- creating whitelist_ips ipset as does not exist."
  ipset create whitelist_ips hash:ip hashsize 4096 maxelem 262144
  if [ -f "$BL_DIR/whitelist_ips.sav" ]; then
    echo "-- importing from save file $BL_DIR/whitelist_ips.sav"
    grep -v "create" $BL_DIR/whitelist_ips.sav | ipset restore 
  fi
fi

loadcustomwhitelist
loadcustomblacklist
loadcustomiptables

# If PSAD is installed then use some of it's good detection work
# to stop attackers.
count=0
if [ -f "/var/log/psad/top_attackers" ]; then
 for ip in `awk '{print $2, $1}' /var/log/psad/top_attackers | grep "^[$DL-]" | awk '{print $2}'`; do
    blacklistit $ip $BLACKLIST
    count=$((count+1))
  done
fi
echo "-- loaded $count entries from /var/log/psad/top_attackers "

#
# Load Standard format blacklist
# Some of them are over zealous, you may want to comment out.
#
loadblacklist \
  "lists-blocklist-de-all" \
  "http://lists.blocklist.de/lists/all.txt"

loadblacklist \
   "emerging-block-ips" \
   "http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt"

loadblacklist \
   "greensnow" \
   "https://blocklist.greensnow.co/greensnow.txt"

loadblacklist \
  "nubi" \
  "https://www.nubi-network.com/list.txt"

loadblacklist \
      "ci-army-malcious" \
        "http://cinsscore.com/list/ci-badguys.txt"

loadblacklist \
      "bruteforceblocker" \
        "http://danger.rulez.sk/projects/bruteforceblocker/blist.php"

loadblacklist \
      "torexitnodes" \
        "https://check.torproject.org/torbulkexitlist"

loadblacklist \
      "spamhaus-org-lasso" \
        "http://www.spamhaus.org/drop/drop.lasso"


loadblacklist \
      "alienvault-reputation" \
        "https://reputation.alienvault.com/reputation.generic"

loadblacklist \
      "pfBlockerNG-malicious-threats-bbcan177_ms1" \
        "https://gist.githubusercontent.com/BBcan177/bf29d47ea04391cb3eb0/raw"

loadblacklist \
      "pfBlockerNG-malicious-threats-bbcan177_ms3" \
        "https://gist.githubusercontent.com/BBcan177/d7105c242f17f4498f81/raw"

loadblacklist \
      "haley-ssh" \
        "http://charles.the-haleys.org/ssh_dico_attack_hdeny_format.php/hostsdeny.txt"


#
# special cases, custom formats blacklist
# COLUMNS with range subnets
#
# Obtain List of badguys from dshield.org
# https://isc.sans.edu/feeds_doc.html
  BL_NAME="dshield.org-top-20"
  BL_URL="https://feeds.dshield.org/block.txt"

function convert {
 while read line; do
  awk '/[^0-9]/ { printf "%s/%s\n",$1,$3 }'
 done
}

   #curl $BL_URL | dos2unix | grep -E "^[1-9]" | convert

  BL_FILE="$BL_DIR/$BL_NAME.txt"
  if [ ! -f "$BL_FILE" ] || [ $(date +%s -r "$BL_FILE") -lt $(date +%s --date="$BL_AGE") ]; then
    echo "-- getting fresh $BL_NAME from $BL_URL"
    wget -q -t 2 --output-document=$BL_FILE $BL_URL --no-check-certificate
  fi
  
  if [ -f "$BL_FILE" ]; then
    echo "-- loading $BL_NAME from $BL_FILE"
    for net in `grep -E "^[1-9]" $BL_FILE | convert`; do
      blacklistit $net $BL_NAME
    done
  fi
 


# swap in the new sets.
ipset swap blacklist_ips_n blacklist_ips
ipset swap blacklist_nets_n blacklist_nets
ipset swap whitelist_ips_n whitelist_ips

# show before blacklist and after counts.
complete_msg="blacklist_ips: current=`ipset --list blacklist_ips_n | egrep '^[1-9]' | wc -l` \
  previous=`ipset --list blacklist_ips  | egrep '^[1-9]' | wc -l` \
  blacklist_nets: previous=`ipset --list blacklist_nets | egrep '^[1-9]' | wc -l` \
  current=`ipset --list blacklist_nets_n | egrep '^[1-9]' | wc -l`"

logmessage "$complete_msg"

# only send email if problems.
if [ -n "$MAIL_ADMIN" ] && [ -n "$ERROR_MSGS" ]; then
  echo -e "${complete_msg}\n${ERROR_MSGS}" | mail -s "$LOG_TAG $HOST_NAME" $MAIL_ADMIN
fi


# save memory space by destroying the temporary swap ipset
ipset destroy blacklist_ips_n
ipset destroy blacklist_nets_n
ipset destroy whitelist_ips_n

# save our ipsets for quick import on reboot.
ipset save blacklist_ips  > $BL_DIR/blacklist_ips.sav
ipset save blacklist_nets > $BL_DIR/blacklist_nets.sav
ipset save whitelist_ips  > $BL_DIR/whitelist_ips.sav

logmessage "NGO_FW script completed"